# Generated by Django 6.0.3 on 2026-04-01 01:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_music_audio_file_alter_music_cover_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_musics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MusicLike',
        ),
    ]
